FROM node:21-bookworm
WORKDIR /home/node/workspaces

# ARG USERNAME=vscode
# ARG USER_ID=1001
# ARG USER_GID=${USER_ID}
# ARG NPM_GLOBAL=/usr/local/share/npm-global
# RUN groupadd --gid ${USER_GID} ${USERNAME} \
#     && useradd -s /bin/bash --uid ${USER_ID} --gid ${USER_GID} -m ${USERNAME}

RUN apt-get update && apt-get install -y sudo\
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
    # && echo ${USERNAME} ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/${USERNAME} \
    # && chmod 0440 /etc/sudoers.d/${USERNAME} \
    # && chown -R vscode /home/vscode \
    # && chmod -R 774 /home/vscode/
    
# pnpmを有効化
ENV PNPM_HOME="/usr/local/share/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

RUN pnpm config set store-dir /usr/local/share/.pnpm-store

# typescriptを導入
RUN pnpm add -g typescript @types/node ts-node

# biomeを導入
RUN pnpm add -g @biomejs/biome
RUN pnpm dlx @biomejs/biome init
